### ISSUE TITLE
Why not use env preset?

### ISSUE THREAD

**Issue by billyjanitsch** [avajs/babel-preset-stage-4#16]
I'm probably missing something, but out of curiosity: why doesn't AVA just use `["@babel/preset-env", {"targets": {"node": "current"}}]`? Babel already has conditional feature support based on the currently running node version built-in -- it seems odd for AVA to reimplement this.

**Comment by novemberborn** [comment]
It's an attempt to limit the number of plugins included when installing AVA. We also don't want to load any polyfills and I'm not sure how `preset-env` interacts with that.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by billyjanitsch** [comment]
I see, you don't want to depend on anything that isn't needed to support even the lowest compatible node version. Makes sense.

The env preset doesn't load or depend on any polyfills by default, FWIW (though you can configure it to automatically include polyfill requires if you depend on a polyfill yourself).
