### ISSUE TITLE
Dependency Version Mismatch 

### ISSUE THREAD

**Issue by ghost** [avajs/babel-preset-stage-4#18]
Related to #17

`@babel/plugin-check-constants` has been released until v7.0.0-beta.38 but the source code of the package is missing in the babel repo.

See babel/babel#7552

**Comment by ghost** [comment]
`@babel/plugin-check-constants` was a spec violation.

Babel will now insert throw statements in the generated code instead.

**Comment by ghost** [comment]
I think it would be fine to remove this plugin.

**Comment by novemberborn** [comment]
OK makes sense. Would you like to do the honors @clemtrek?

**Comment by ghost** [comment]
Yeah, thanks.
