### ISSUE TITLE
ES2018 stage 4 proposals

### ISSUE THREAD

**Issue by sindresorhus** [avajs/babel-preset-stage-4#7]
Not relevant yet, but just a reminder to check the proposals once in a while. TC39 will soon have a meeting and after that, some stage 3 proposals will probably become stage 4.

https://github.com/tc39/proposals
http://2ality.com/2017/02/ecmascript-2018.html

**Comment by novemberborn** [comment]
https://github.com/avajs/babel-preset-stage-4/pull/13 adds support for those proposals for which I could find official Babel plugins.
